### ISSUE TITLE
scikit-learn-contrib?

### ISSUE THREAD

**Issue by tdhock** [aldro61/mmit#31]
I wonder if it would be worth it to try to get mmit into scikit-learn-contrib?

https://github.com/scikit-learn-contrib

**Comment by aldro61** [comment]
It might be a tad difficult since not all our code is sklearn compatible. For instance, the GridSearchCV class (https://github.com/aldro61/mmit/blob/master/mmit/model_selection.py#L152) is based on an sklearn class but it was modified to support pruning.

It's a good idea, but I'm not sure if it's worth it for now.

**Comment by tdhock** [comment]
no problem!

Welcome back to work btw! hope you enjoyed your time off!

**Comment by aldro61** [comment]
Thanks Toby! Yes, it was great :) Hope that you're well! Let's meet next week if you're available.

Closing this issue for now.
